### PR TITLE
add a precompile workload

### PR DESCRIPTION
**Pull request by KristofferC**
Benchmark (first time call):

```julia
function test()
    for dim in (2, 3)
        v = ones(Tensor{1, dim, Float64,})
        σ = one(SymmetricTensor{2, dim, Float64})
        F = one(Tensor{2, dim, Float64,})
        E = one(SymmetricTensor{4, dim, Float64})
        C = one(Tensor{4, dim, Float64,})
        v * 1.0
        v ⋅ v
        v ⊗ v
        σ ⋅ v
        σ * 1.0
        F ⋅ v
        F * 1.0
        σ ⊡ σ
        F ⊡ F
        E ⊡ σ
        C ⊡ F
        E * 1.0
        C * 1.0
    end
end
```

```julia
# PR
julia> @time @eval test()
  0.108281 seconds (397.91 k allocations: 26.521 MiB, 177.42% compilation time)

# Master
julia> @time @eval test()
  0.935148 seconds (3.00 M allocations: 203.775 MiB, 2.72% gc time, 186.47% compilation time)
```

These are the things that still compile even after this when running the function:

```julia
precompile(Tuple{SIMD.Intrinsics.var"##s8#111", Vararg{Any, 5}})
precompile(Tuple{typeof(Base.getindex), Base.Dict{DataType, String}, Type})
precompile(Tuple{SIMD.Intrinsics.var"##s8#105", Vararg{Any, 6}})
precompile(Tuple{typeof(Base.Iterators.product), Base.UnitRange{Int64}, Vararg{Base.UnitRange{Int64}}})
precompile(Tuple{SIMD.Intrinsics.var"##s8#95", Vararg{Any, 6}})
precompile(Tuple{typeof(SIMD.Intrinsics.llvm_name), Symbol, Int64, Type})
precompile(Tuple{typeof(SIMD.Intrinsics.suffix), Int64, Type{Float64}})
precompile(Tuple{typeof(Base.cconvert), Type, Tuple{VecElement{Float64}, VecElement{Float64}}})
precompile(Tuple{SIMD.Intrinsics.var"##s7#28", Vararg{Any, 6}})
precompile(Tuple{typeof(SIMD.Intrinsics.llvm_type), Type{Tuple{VecElement{Float64}, VecElement{Float64}, VecElement{Float64}}}})
precompile(Tuple{typeof(SIMD.Intrinsics.llvm_type), Type{NTuple{4, VecElement{Float64}}}})
precompile(Tuple{typeof(Base.cconvert), Type, NTuple{4, VecElement{Float64}}})
precompile(Tuple{typeof(Main.test)})
precompile(Tuple{typeof(Tensors.apply_all), Type{Tensors.Tensor{1, 2, T, M} where M where T}, Tensors.var"#102#103"{Float64}})
precompile(Tuple{typeof(Tensors.apply_all), Type{Tensors.Tensor{1, 3, T, M} where M where T}, Tensors.var"#102#103"{Float64}})
```

Not sure why yet.

### CODE REVIEW

**Comment by timholy** [comment]
May be related to https://github.com/JuliaLang/julia/issues/47960. I've thought of three main possibilities:
- there's a bug in our caching code
- there's a bug/limitation in SnoopPrecompile
- these methods were all compiled but not cached prior to `compilecache` being called for this package. It's noteworthy that they are all external methods and do not involve any types that appear to be specific to this package. Try moving the last two to Tensors and see if they precompile there.

**Comment by timholy** [comment]
If you want to debug the latter, one thing you could try:
- temporarily add `MethodAnalysis` as a dependency to this package
- at top-level in this package, prior to your `@precompile_all_calls`, do something like this:

```julia
using MethodAnalysis
display(methodinstances(Tensors.apply_all, (Type{Tensors.Tensor{1, 2}}, Any)))
```
and then watch the log during precompilation to see if those already exist.

**Comment by KristofferC** [comment]
>  It's noteworthy that they are all external methods and do not involve any types that appear to be specific to this package. Try moving the last two to Tensors and see if they precompile there.

I would have thought

```
precompile(Tuple{typeof(Tensors.apply_all), Type{Tensors.Tensor{1, 2, T, M} where M where T}, Tensors.var"#102#103"{Float64}})
precompile(Tuple{typeof(Tensors.apply_all), Type{Tensors.Tensor{1, 3, T, M} where M where T}, Tensors.var"#102#103"{Float64}})
```

belong to Tensors (this package)?

I'll try precompile some stuff in SIMD.jl and see if it sticks there.

**Comment by timholy** [comment]
Shoot. I mistakenly took the org name as the package name. Yeah, seems weird.

**Comment by timholy** [comment]
But https://github.com/Ferrite-FEM/Tensors.jl/pull/190#issuecomment-1367871359 might still be useful to figure out where the bug is. If something is precompiling it before you get to `@precompile_all_calls`, that suggests a bug in the "what should we keep?" caching mechanism. If instead it doesn't exist until after the `@precompile_all_calls`, it suggests *another* bug in SnoopPrecompile failing to tag things.

**Comment by timholy** [comment]
I see `apply_all` is a generated function. I don't think we have any of those in our test suites. If you do (in the REPL)
```julia
using MethodAnalysis
mis = methodinstances(Tensors.apply_all, (Type{Tensors.Tensor{1, 2}}, Any))
for mi in mis
    @show mi.def.module
end
```
what do you get?

**Comment by KristofferC** [comment]
I'll try the stuff from the latest comment but with https://github.com/eschnett/SIMD.jl/pull/101 I now only have:

```julia
julia> @time @eval test();
precompile(Tuple{typeof(SIMD._unsafe_convert), Type{Float64}, Float64})
precompile(Tuple{typeof(Base.getindex), Base.Dict{DataType, String}, Type})
precompile(Tuple{SIMD.Intrinsics.var"##s8#105", Vararg{Any, 6}})
precompile(Tuple{typeof(Base.convert), Type{Tuple{VecElement{Float64}, VecElement{Float64}}}, Tuple{VecElement{Float64}, VecElement{Float64}}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Tuple{VecElement{Float64}, VecElement{Float64}}}, Tuple{VecElement{Float64}, VecElement{Float64}}})
precompile(Tuple{typeof(Base.convert), Type{NTuple{4, VecElement{Float64}}}, NTuple{4, VecElement{Float64}}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{NTuple{4, VecElement{Float64}}}, NTuple{4, VecElement{Float64}}})
  0.078406 seconds (216.25 k allocations: 14.494 MiB, 11.40% gc time, 183.82% compilation time)
```

left. I don't know where the `Tensors.apply_all` went. In fact, when I try running the original example as the first post I no longer see it getting printed anymore...

**Comment by KristofferC** [comment]
I'll try the stuff from the latest comment in a sec. With https://github.com/eschnett/SIMD.jl/pull/101 I now only have:

```julia
precompile(Tuple{typeof(SIMD._unsafe_convert), Type{Float64}, Float64})
precompile(Tuple{typeof(Base.getindex), Base.Dict{DataType, String}, Type})
precompile(Tuple{SIMD.Intrinsics.var"##s8#105", Vararg{Any, 6}})
precompile(Tuple{typeof(Base.Iterators.product), Base.UnitRange{Int64}, Vararg{Base.UnitRange{Int64}}})
precompile(Tuple{typeof(Base.cconvert), Type, Tuple{VecElement{Float64}, VecElement{Float64}}})
precompile(Tuple{typeof(Base.convert), Type{Tuple{VecElement{Float64}, VecElement{Float64}}}, Tuple{VecElement{Float64}, VecElement{Float64}}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{Tuple{VecElement{Float64}, VecElement{Float64}}}, Tuple{VecElement{Float64}, VecElement{Float64}}})
precompile(Tuple{typeof(Base.cconvert), Type, NTuple{4, VecElement{Float64}}})
precompile(Tuple{typeof(Base.convert), Type{NTuple{4, VecElement{Float64}}}, NTuple{4, VecElement{Float64}}})
precompile(Tuple{typeof(Base.unsafe_convert), Type{NTuple{4, VecElement{Float64}}}, NTuple{4, VecElement{Float64}}})
precompile(Tuple{typeof(Main.test)})
precompile(Tuple{typeof(Tensors.apply_all), Type{Tensors.Tensor{1, 2, T, M} where M where T}, Tensors.var"#102#103"{Float64}})
precompile(Tuple{typeof(Tensors.apply_all), Type{Tensors.Tensor{1, 3, T, M} where M where T}, Tensors.var"#102#103"{Float64}})
  0.092978 seconds (231.81 k allocations: 15.410 MiB, 9.66% gc time, 180.34% compilation time)
```

So the `SIMD.Intrinsics.llvm_type`, `SIMD.Intrinsics.llvm_name`, are gone at least and slightly better latency.

**Comment by KristofferC** [comment]
> If you want to debug the latter, one thing you could try:...

```julia
julia> using Tensors
[ Info: Precompiling Tensors [48a634ad-e948-5137-8d70-aa71f2a747f4]
# Before precompile execution
Core.MethodInstance[]
# After precompile execution
1-element Vector{Core.MethodInstance}:
 MethodInstance for Tensors.apply_all(::Type{Tensors.Tensor{1, 2}}, ::Tensors.var"#102#103"{Float64})
```

So it seems it gets defined by the precompile workload

----------

>  If you do (in the REPL)


```julia
julia> using MethodAnalysis

julia> mis = methodinstances(Tensors.apply_all, (Type{Tensors.Tensor{1, 2}}, Any))
1-element Vector{Core.MethodInstance}:
 MethodInstance for Tensors.apply_all(::Type{Tensor{1, 2}}, ::Tensors.var"#102#103"{Float64})

julia> for mi in mis
           @show mi.def.module
       end
mi.def.module = Tensors
```

**Comment by KristofferC** [comment]
Note that if I copy paste

```
  precompile(Tuple{typeof(Tensors.apply_all), Type{Tensors.Tensor{1, 2, T, M} where M where T}, Tensors.var"#102#103"{Float64}})
    precompile(Tuple{typeof(Tensors.apply_all), Type{Tensors.Tensor{1, 3, T, M} where M where T}, Tensors.var"#102#103"{Float64}})
```

into the precompile workload, they do in fact get cached.

**Comment by timholy** [comment]
Looks like a bug in the caching code. The fact that the module is Tensors makes this very weird. Next step might be a MWE that we could add to Julia's test suite.

**Comment by KristofferC** [comment]
I'll try reduce it a bit.

**Comment by KristofferC** [comment]
I managed to reduce this quite a lot (and there are now no generated functions):

```julia
module Tensors
struct Tensor{dim} 
    data::NTuple{dim, Float64}
end

function apply_all(S::Type{Tensor{dim}}, f::Function) where {dim}
    Tensor{dim}((f(1), f(1)))
end

@inline Base.fill(el::Float64, S::Type{Tensor{dim}}) where {dim} = apply_all(Tensor{dim}, i -> el)

using SnoopPrecompile

@precompile_all_calls begin
    v = fill(1.0, Tensor{2})
end

end # module
```

Precompiling this and running

`tesit.jl`:
```julia
using Tensors

function test()
    for dim in [2]
        v = fill(1.0, Tensors.Tensor{dim})
    end
end

test()
```

```
❯ julia --project --trace-compile=stderr --startup-file=no testit.jl 
precompile(Tuple{typeof(Main.test)})
precompile(Tuple{typeof(Tensors.apply_all), Type{Tensors.Tensor{2}}, Tensors.var"#1#2"{Float64}})
```

If the `@inline` on `Base.fill` is removed, the `Tensors.apply_all` goes away.

**Comment by KristofferC** [comment]
I tried the new PkgCacheInspector on `bad.ji` (without the explicit precompile statement that thus requires compilation) and `good.ji` which is when the explicit precompile statement is added:

```
julia> info_cachefile(Base.identify_package("Ts"),"/Users/kristoffercarlsson/.julia/compiled/v1.9/Ts/bad.ji")
Contents of /Users/kristoffercarlsson/.julia/compiled/v1.9/Ts/bad.dylib:
  modules: Any[Ts]
  2 external methods
  2 external targets
  3 edges
  file size:   68912 (67.297 KiB)
  Segment sizes (bytes):
  system:      13584 ( 82.32%)
  isbits:       1433 (  8.68%)
  symbols:       281 (  1.70%)
  tags:          210 (  1.27%)
  relocations:   969 (  5.87%)
  gvars:           8 (  0.05%)
  fptrs:          16 (  0.10%)

julia> info_cachefile(Base.identify_package("Ts"),"/Users/kristoffercarlsson/.julia/compiled/v1.9/Ts/good.ji")
Contents of /Users/kristoffercarlsson/.julia/compiled/v1.9/Ts/good.dylib:
  modules: Any[Ts]
  2 external methods
  23 new specializations of external methods (Base 95.7%, Base.Iterators 4.3%)
  5 external methods with new roots
  1119 external targets
  748 edges
  file size:   300720 (293.672 KiB)
  Segment sizes (bytes):
  system:      168608 ( 82.18%)
  isbits:       24585 ( 11.98%)
  symbols:        330 (  0.16%)
  tags:          2222 (  1.08%)
  relocations:   9315 (  4.54%)
  gvars:           40 (  0.02%)
  fptrs:           64 (  0.03%)
```

**Comment by KristofferC** [comment]
In this MWE, it is enough to specialize on `f` actually to remove it:

```
h(::Type{T{dim}}, f::F) where {dim, F} = T{dim}((1.0, 1.0))
```

**Comment by KristofferC** [comment]
Since this is not really related to Tensors anymore, I opened an issue on Julia: https://github.com/JuliaLang/julia/issues/48048

**Pull request merged**
