### PR TITLE
Correction of bug in minorsymmetric

### PR DESCRIPTION
**Pull request by jfbarthelemy**
The right formula for "minorsymmetrization" is `(Sᵢⱼₖₗ+Sⱼᵢₖₗ+Sᵢⱼₗₖ+Sⱼᵢₗₖ)/4` and not `(Sᵢⱼₖₗ+Sⱼᵢₖₗ+Sᵢⱼₖₗ+Sᵢⱼₗₖ)/4`

### CODE REVIEW

**Comment by KnutAM** [comment]
Nice, this would introduce hard to find bugs! I would think a test to catch this would be nice to add, what about
```julia
for dim=1:3
a,b=[rand(Tensor{2,dim}) for _ in 1:2];
as,bs = symmetric.([a,b]);
@test minorsymmetric(a⊗b)≈as⊗bs
end
```
?

**Comment by jfbarthelemy** [comment]
> Nice, this would introduce hard to find bugs! I would think a test to catch this would be nice to add, what about
> 
> ```julia
> for dim=1:3
> a,b=[rand(Tensor{2,dim}) for _ in 1:2];
> as,bs = symmetric.([a,b]);
> @test minorsymmetric(a⊗b)≈as⊗bs
> end
> ```
> 
> ?

**Comment by jfbarthelemy** [comment]
> Nice, this would introduce hard to find bugs! I would think a test to catch this would be nice to add, what about
> 
> ```julia
> for dim=1:3
> a,b=[rand(Tensor{2,dim}) for _ in 1:2];
> as,bs = symmetric.([a,b]);
> @test minorsymmetric(a⊗b)≈as⊗bs
> end
> ```
> 
> ?

**Comment by jfbarthelemy** [comment]
> Nice, this would introduce hard to find bugs! I would think a test to catch this would be nice to add, what about
> 
> ```julia
> for dim=1:3
> a,b=[rand(Tensor{2,dim}) for _ in 1:2];
> as,bs = symmetric.([a,b]);
> @test minorsymmetric(a⊗b)≈as⊗bs
> end
> ```
> 
> ?

Sure. By the way the test you propose doesn't pass with the old version and passes with the new one.

**Comment by fredrikekre** [comment]
Thank you!

**Pull request merged**
